export const GROUPS = {
  "accessories": [
    "cruise-control",
    "grip-glue",
    "heated-grips",
    "kickstand-pad",
    "motorcycle-cover",
    "tyre-shine",
    "windscreen-bolts",
  ],
  "brakes": [
    "brake-caliper-repair-kit",
    "brake-cleaner",
    "brake-disc-front",
    "brake-disc-rear",
    "brake-fluid",
    "brake-pads",
    "brake-piston-grease",
    "brake-pump-repair-kit",
    "maintenance-package",
  ],
  "clothing--merchandise": [
    "clothing-care",
    "pedal-for-kids",
    "helmets",
    "gloves",
    "jackets--pants",
    "boots" 
  ],
  "suspension--steering": [
    "front-forks--fork-tubes",
    "shock-absorber--rear-shock",
    "triple-tree--steering-stem",
    "steering-bearings"
  ],
  "wheels--tyres": [
      "rims--wheels",
      "hubs--spokes",
      "tires-front--rear",
      "inner-tubes",
      "wheel-axle--spacers"
  ],
  "frame--bodywork": [
      "frame--subframe",
      "footpegs--rearsets",
      "fairings--side-panels",
      "seat--seat-covers"
  ],
  "exhaust": [
      "complete-exhaust-systems",
      "headers--downpipes",
      "mufflers--silencers",
      "exhaust-clamps--gaskets"
  ],
  "cooling": [
      "radiator",
      "radiator-cap--hoses",
      "water-pump"
  ],
  "engine--transmission": [
      "engine-blocks--crankcases",
      "pistons--cylinder-kits",
      "camshaft--valvetrain-parts",
      "gearbox--transmission-parts",
      "gaskets--seals"
  ],
  "drivetrain": [
    "chain-and-sprockets-kit",
    "chain-guard",
    "chain-oiler-system",
    "chains",
    "clutch",
    "clutch-plate",
    "sprockets",
  ],
  "electric": [
    "alternator",
    "battery",
    "battery-booster",
    "battery-charger",
    "battery-charger-accessories",
    "brake-light-switch",
    "clutch-switch",
    "contact-cleaner",
    "flasher-relay",
    "ignition-coil",
    "regulator",
    "spark-plug-cap",
    "spark-plug-wire",
    "sparkplug",
    "starter",
    "starter-relay",
    "tape",
  ],
  "filters": [
    "air-filter",
    "air-filter-cleaner",
    "air-filter-oil",
    "fuel-filter",
    "oil--fluids",
    "oil-filter",
  ],
  "fuel--additives": [
    "cleaner",
    "e10-additive",
    "ecomaxx-fuel",
    "octane-booster",
    "stabilizer",
  ],
  "fuel-tank": [
    "fuel-hose",
    "fuel-pump",
    "fuel-tank-cleaner",
    "fuel-tank-deruster",
    "fuel-tank-sealant",
    "quick-connector",
  ],
  "handlebar--controls": [
    "brake-lever",
    "brake-line",
    "clutch-cable",
    "clutch-lever",
    "mirror-adapter",
    "mirror-holder",
    "mirror-left",
    "mirror-right",
    "mirror-set",
    "throttle-cable",
  ],
  "locks": [
    "chain-lock",
    "disc-brake-lock",
    "ground-wall-anchor",
    "lock-accessory",
    "lock-reminder",
    "u-lock",
  ],
  "luggage": [
    "backpack",
    "bag-left",
    "bag-right",
    "bag-set",
    "cargo-net",
    "case-set",
    "luggage-rack",
    "luggage-roll",
    "saddle-bag",
    "suitcase-left",
    "suitcase-right",
    "tank-bag",
    "tank-bag-mounting",
    "top-case",
    "travelbag-kit",
  ],
  "maintenance": [
    "alternator-cover-gasket",
    "assembly-paste",
    "bearing-grease",
    "carburetor-cleaner",
    "chain-cleaner",
    "chain-spray",
    "clamps",
    "clutch-cover-gasket",
    "drain-plug",
    "drain-plug-washer",
    "engine-oil-cleaner",
    "gasket-paper",
    "liquid-gasket",
    "lithium-grease",
    "molybdeen-grease",
    "multispray",
    "penetrating-oil",
    "primary-cover-gasket",
    "radiator-cleaner",
    "valve-cover-gasket",
  ],
  "navigation--intercom--telephone": [
    "intercom",
    "navigation-system",
    "phone-holder",
    "phone-holder-accessoires",
    "phone-holder-mounting",
    "gps-tracker--alarm-systems"
  ],
  "oil--fluids": [
    "2-stroke-oil",
    "clutch-fluid",
    "engine-coolant",
    "engine-oil",
    "fork-oil",
    "shock-absorber-oil",
    "transmission-oil",
  ],
  "overhaul-kits": [
    "carburettor-repair-kit",
    "front-fork-oil-seal",
    "front-fork-repair-kit",
    "fuel-tap-repair-kit",
    "gaskets",
    "link-system-bearing",
    "shock-absorber-bearing",
    "steering-bearing",
    "swingarm-bearing",
    "wheel-bearing",
  ],
  "tools": [
    "brake-bleeder",
    "cable-lubricator-tool",
    "carburetor-screwdriver",
    "chain-tools",
    "front-fork-tools",
    "front-wheel-axle-tool",
    "gasket-scraper",
    "spark-plug-wrench",
    "spring-puller",
    "stethoscope",
    "synchronous-tester",
    "thread-repair",
    "tire-pressure-gauge",
    "voltage-tester",
    "oil-filter-wrench",
  ],
  "wash--shine": [
    "brush",
    "bug-spray",
    "chrome--alu-polish",
    "cleaning-cloth",
    "cleaning-set",
    "cleaning-supplies",
    "corrosion-protection",
    "degreaser",
    "exhaust-plug",
    "polish--wax",
    "seat-spray",
    "silicone-spray",
    "sponge",
    "wax-spray",
    "wheel-cleaner",
  ],
  "workshop-equipment": [
    "assortment-boxes",
    "auxiliary-fuel-tank",
    "funnel",
    "handlebar-harness",
    "hand-cleaner",
    "jerrycan",
    "magnetic-scale",
    "mechanics-bar-stool",
    "motorcycle-lift",
    "oil-collection-tray",
    "paddock-stand",
    "paddock-stand-adapter",
    "threadlocker",
    "tie-down-straps",
    "vice-jaws",
    "wheel-chock",
    "workshop-glove",
    "workshop-manual",
  ],
};

